### ISSUE TITLE
Azure: Standard_L8as_v3 not recognized by cloud setup

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-machine-image#439]
instance: Standard_L8as_v3
Scylla 2022.2.3 + machine image 2022.2.3

```
root@gc-scylla-test001:/home/azureuser# sudo /opt/scylladb/scylla-machine-image/scylla_cloud_io_setup  
 
 
ERROR:root:This is not a recommended Azure Cloud instance setup for auto local disk tuning. 
Traceback (most recent call last): 
 File "/opt/scylladb/scylla-machine-image/libexec/scylla_cloud_io_setup", line 357, in <module> 
   io.generate() 
 File "/opt/scylladb/scylla-machine-image/libexec/scylla_cloud_io_setup", line 298, in generate 
   raise UnsupportedInstanceClassError() 
TypeError: UnsupportedInstanceClassError() missing 1 required positional argument: 'Exception' 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
 File "/opt/scylladb/scylla-machine-image/libexec/scylla_cloud_io_setup", line 359, in <module> 
   except UnsupportedInstanceClassError as e: 
TypeError: catching classes that do not inherit from BaseException is not allowed 
root@gc-scylla-test001:/home/azureuser#
```

**Comment by tarzanek** [comment]
@syuu1228 @yaronkaikov ^

**Comment by tarzanek** [comment]
actually, even with above, the fallback to iotune should still work, is above an iotune bug?

**Comment by yaronkaikov** [comment]
@tarzanek is it possible to work with `5.2` or `2023.1`? all Azure verification started officially from those releases

**Comment by tarzanek** [comment]
@gcarmin can you use 2023.1 RC ?

**Comment by yaronkaikov** [comment]
Any Official release starting from 2023.1.X and 2024.1.X should support this type. 
Closing this issue, if you facing this issue in an official release, please feel free to open it again
